/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_RXTXPort_BetterSerialInputStream */

#ifndef _Included_gnu_io_RXTXPort_BetterSerialInputStream
#define _Included_gnu_io_RXTXPort_BetterSerialInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef gnu_io_RXTXPort_BetterSerialInputStream_MAX_SKIP_BUFFER_SIZE
#define gnu_io_RXTXPort_BetterSerialInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef gnu_io_RXTXPort_BetterSerialInputStream_SLEEP_TIME
#define gnu_io_RXTXPort_BetterSerialInputStream_SLEEP_TIME 10LL
#ifdef __cplusplus
}
#endif
#endif
