/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_io_CommPortIdentifier_PortType */

#ifndef _Included_gnu_io_CommPortIdentifier_PortType
#define _Included_gnu_io_CommPortIdentifier_PortType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
